### ISSUE TITLE
Bot becomes unresponsive after sharing contact (phone number) in signup form

### ISSUE THREAD

**Issue by gcmartinelli** [fczuardi/gsheetsbot#29]
![signup_bug](https://cloud.githubusercontent.com/assets/1650735/20934749/600ea43a-bbc3-11e6-812c-a8f1fffc9a2e.jpg)

After sharing contact the bot became unresponsive. I share the contact again,  with no  effect.  Questions only started being asked again after sending a random text ("?"), by which time the bot had skipped at least one question ('what's your e-mail?')

**Comment by fczuardi** [comment]
can you paste the logs for this conversation? Is this reproducible?

**Comment by fczuardi** [comment]
ok, found the bug and the reproduction steps here, should be simple to fix
